--// File Generated By Fox-Warrior's Resources Generator Version 2.06 \\--

if (SERVER) then
	resource.AddFile( "sound/shotgun_earrape.wav")
	resource.AddFile( "materials/models/weapons/v_models/dbarrel/doubleba.vmt" )
	resource.AddFile( "materials/models/weapons/w_models/dbarrel/doubleba.vmt" )
	resource.AddFile( "models/weapons/w_double_barrel_shotgun.mdl" )
	resource.AddFile( "models/weapons/v_doublebarrl.mdl" )
end